### ISSUE TITLE
Support Kubernetes 1.1

### ISSUE THREAD

**Issue by jvmirdel** [pires/kubernetes-elk-cluster#8]
error validating data: found invalid field source for v1.Volume; if you choose to ignore these errors, turn validation off with --validate=false

```
    volumeMounts:
    - mountPath: /certs
      name: certs
  volumes:
  - name: storage
    source:
      emptyDir: {}
  - name: certs
    source:
      hostPath:
        path: /tmp
```

I am at tag 108f879610829b888001db7d7bd38cd03508dcab     Fixes #5

I tried switching certs to source: emptyDir: {} but that didn't affect the error message

**Comment by pires** [comment]
I need to update this.

**Comment by jvmirdel** [comment]
I figured out a way to get past the volume change

```
  volumes:
      - emptyDir:
          medium: ""
        name: "storage"
      - hostPath:
          path: "/tmp"
        name: "certs"
```

but now I have a kibana name resolution issue

{"name":"Kibana","hostname":"kibana-qzxsf","pid":9,"level":50,"err":"Request error, retrying -- getaddrinfo ENOTFOUND elasticsearch.default.svc.cluster.local","msg":"","time":"2015-11-21T17:24:50.911Z","v":0}

Looks like the dns resolution is intermittent
